# Generated by Django 4.0.3 on 2022-05-07 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('items', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('game_code', models.UUIDField(default=uuid.UUID('b65fd0c4-d81d-4302-ad63-170e5957d24c'), editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('agents_behaviors', models.CharField(choices=[(1, 'Optimal'), (2, 'SubOptimal')], default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=5)),
                ('target', models.CharField(max_length=5)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('round', models.SmallIntegerField(blank=True, null=True)),
                ('time_stamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee', models.CharField(blank=True, max_length=255, null=True)),
                ('round', models.SmallIntegerField(blank=True, null=True)),
                ('time_stamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_mission_score', models.PositiveIntegerField(blank=True, null=True)),
                ('was_killer', models.BooleanField(blank=True, default=False, null=True)),
                ('killer_round', models.SmallIntegerField(blank=True, default=-1, null=True)),
                ('game_appearance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.gameappearance')),
                ('votes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.vote')),
            ],
        ),
    ]
