# Generated by Django 4.0.2 on 2022-03-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('items', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee', models.CharField(max_length=255)),
                ('round', models.SmallIntegerField()),
                ('time_stamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_mission_score', models.PositiveIntegerField(blank=True, null=True)),
                ('was_killer', models.BooleanField(blank=True, default=False, null=True)),
                ('killer_round', models.SmallIntegerField(blank=True, null=True)),
                ('game_appearance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research.gameappearance')),
                ('votes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.vote')),
            ],
        ),
    ]
