# Generated by Django 4.0.3 on 2022-05-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='owner',
            new_name='researcher',
        ),
    ]
