# Generated by Django 4.0.3 on 2022-05-09 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='game_configuration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.gameconfiguration'),
        ),
        migrations.AddField(
            model_name='research',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.participant'),
        ),
        migrations.AddField(
            model_name='research',
            name='research_description',
            field=models.TextField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='research',
            name='research_name',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='gameconfiguration',
            name='game_code',
            field=models.UUIDField(default=uuid.UUID('3f37518d-e43c-467c-9303-733082b1ed28'), editable=False, primary_key=True, serialize=False),
        ),
    ]
