# Generated by Django 4.0.3 on 2022-05-09 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_research_game_configuration_research_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='research',
            name='participants',
        ),
        migrations.AddField(
            model_name='interactions',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
        migrations.AddField(
            model_name='participant',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
        migrations.AddField(
            model_name='vote',
            name='participant_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.participant'),
        ),
        migrations.AlterField(
            model_name='gameconfiguration',
            name='game_code',
            field=models.UUIDField(default=uuid.UUID('a032e0f2-714a-4c86-bb40-6059db662343'), editable=False, primary_key=True, serialize=False),
        ),
    ]
