# Generated by Django 4.0.3 on 2022-05-09 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_remove_participant_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfiguration',
            name='game_code',
            field=models.UUIDField(default=uuid.UUID('eaf76abb-f96b-41b0-84af-ce52154fa360'), editable=False, primary_key=True, serialize=False),
        ),
    ]
