# Generated by Django 4.0.3 on 2022-05-12 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_gameconfiguration_game_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='game_configuration',
        ),
        migrations.AddField(
            model_name='gameconfiguration',
            name='research',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
        migrations.AlterField(
            model_name='gameconfiguration',
            name='game_code',
            field=models.UUIDField(default=uuid.UUID('f09f4dfa-1c96-49d8-95e9-e4bc9bc36f67'), editable=False, primary_key=True, serialize=False),
        ),
    ]
