# Generated by Django 4.0.2 on 2022-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_participant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=5, null=True)),
                ('target', models.CharField(blank=True, max_length=5, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('round', models.SmallIntegerField(blank=True, null=True)),
                ('time_stamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
