# Generated by Django 4.0.3 on 2022-05-12 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_remove_research_game_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='game_appearance',
        ),
        migrations.AddField(
            model_name='gameappearance',
            name='participant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='research.participant'),
        ),
        migrations.AlterField(
            model_name='gameconfiguration',
            name='game_code',
            field=models.UUIDField(default=uuid.UUID('42d1f18c-2902-499a-acd9-dafcc239cc7c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gameconfiguration',
            name='research',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_configuration', to='research.research'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='research.research'),
        ),
    ]
