# Generated by Django 4.0.2 on 2022-03-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_clues_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactions',
            name='source',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='interactions',
            name='target',
            field=models.CharField(max_length=5),
        ),
    ]
