# Generated by Django 4.0.3 on 2022-04-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_interactions_source_alter_interactions_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('agents_behaviors', models.CharField(choices=[(1, 'Optimal'), (2, 'SubOptimal')], default=1, max_length=50)),
            ],
        ),
    ]
