# Generated by Django 4.0.3 on 2022-05-12 18:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_participant_game_appearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameappearance',
            name='participant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_appearance', to='research.participant'),
        ),
        migrations.AlterField(
            model_name='gameconfiguration',
            name='game_code',
            field=models.UUIDField(default=uuid.UUID('f28f1d9d-4175-4558-9351-097818b36336'), editable=False, primary_key=True, serialize=False),
        ),
    ]
