# Generated by Django 4.0.3 on 2022-05-13 10:08

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_alter_gameappearance_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfiguration',
            name='game_code',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
