# Generated by Django 4.0.3 on 2022-05-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_alter_gameconfiguration_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='research_description',
            field=models.TextField(default=None, max_length=150, null=True),
        ),
    ]
