# Generated by Django 4.0.3 on 2022-05-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_alter_gameconfiguration_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactions',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='research.research'),
        ),
        migrations.AlterField(
            model_name='interactions',
            name='source',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='interactions',
            name='target',
            field=models.CharField(max_length=10),
        ),
    ]
